from enum import StrEnum


class LeagueStatus(StrEnum):
    PENDING = "Sin empezar"
    ACTIVE = "En curso"
    FINISHED = "Finalizada"


class LeagueFinalPhasePreset(StrEnum):
    TOP_4_SINGLE_GAME = "TOP_4_SINGLE_GAME"
    TOP_8_SINGLE_GAME = "TOP_8_SINGLE_GAME"
    TOP_8_HOME_AWAY = "TOP_8_HOME_AWAY"
    TOP_6_SINGLE_GAME_WITH_BYES = "TOP_6_SINGLE_GAME_WITH_BYES"
    TOP_16_SINGLE_GAME = "TOP_16_SINGLE_GAME"
    TOP_32_SINGLE_GAME = "TOP_32_SINGLE_GAME"
    NBA_PLAY_IN_TOP_10 = "NBA_PLAY_IN_TOP_10"
    DOUBLE_ELIMINATION_TOP_8 = "DOUBLE_ELIMINATION_TOP_8"
    DOUBLE_ELIMINATION_TOP_16 = "DOUBLE_ELIMINATION_TOP_16"
    CUSTOM = "CUSTOM"


class LeagueCompetitionType(StrEnum):
    LEAGUE = "LEAGUE"
    ELIMINATION = "ELIMINATION"


class LeagueFinalPhaseFormat(StrEnum):
    SINGLE_ELIMINATION = "SINGLE_ELIMINATION"
    DOUBLE_ELIMINATION = "DOUBLE_ELIMINATION"
    PLAY_IN_PLUS_BRACKET = "PLAY_IN_PLUS_BRACKET"
